import React from 'react';
import { Link } from 'react-router-dom';

function Home() {
  const features = [
    {
      icon: '🤖',
      title: 'AI-Powered Questions',
      description: 'Get personalized interview questions generated by advanced AI, tailored to your target role and experience level.',
    },
    {
      icon: '🎯',
      title: 'Smart Feedback',
      description: 'Receive detailed analysis on content, clarity, confidence, and professionalism with actionable improvement tips.',
    },
    {
      icon: '📈',
      title: 'Progress Tracking',
      description: 'Monitor your improvement over time with comprehensive analytics and performance insights.',
    },
    {
      icon: '⏱️',
      title: 'Timed Practice',
      description: 'Practice under realistic time pressure with countdown timers and auto-progression features.',
    },
    {
      icon: '🎤',
      title: 'Voice Recording',
      description: 'Practice speaking naturally with voice recording and automatic transcription capabilities.',
    },
    {
      icon: '📄',
      description: 'Upload your resume for personalized questions that match your background and target positions.',
    },
  ];

  return (
    <div className="bg-light min-vh-100">
      {/* Hero Section */}
      <div className="container-fluid bg-primary text-white py-5">
        <div className="container py-5">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <h1 className="display-4 fw-bold mb-4">
                Master Your Interview Skills with AI
              </h1>
              <p className="lead mb-4">
                Practice with our advanced AI interviewer, get personalized feedback, 
                and land your dream job with confidence.
              </p>
              <div className="d-flex gap-3 flex-wrap">
                <Link to="/signup" className="btn btn-light btn-lg px-4">
                  Start Practicing Free
                </Link>
                <Link to="/login" className="btn btn-outline-light btn-lg px-4">
                  Sign In
                </Link>
              </div>
            </div>
            <div className="col-lg-6 text-center">
              <div className="bg-white bg-opacity-10 rounded-4 p-4 mt-4 mt-lg-0">
                <h3 className="h4 mb-3">🎯 AI-Powered Practice</h3>
                <p className="mb-0">
                  Get real-time feedback and improve your interview performance
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="container py-5">
        <div className="text-center mb-5">
          <h2 className="h1 fw-bold text-primary mb-3">Why Choose InterviewIQ?</h2>
          <p className="lead text-muted">
            Our AI-powered platform provides everything you need to ace your next interview
          </p>
        </div>
        
        <div className="row g-4">
          {features.map((feature, index) => (
            <div key={index} className="col-lg-4 col-md-6">
              <div className="card h-100 border-0 shadow-sm rounded-4 text-center p-4">
                <div className="card-body">
                  <div className="display-4 mb-3">{feature.icon}</div>
                  <h3 className="h4 fw-bold text-primary mb-3">{feature.title}</h3>
                  <p className="text-muted">{feature.description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-primary text-white py-5">
        <div className="container text-center py-4">
          <h2 className="h1 fw-bold mb-3">Ready to Ace Your Next Interview?</h2>
          <p className="lead mb-4">
            Join thousands of professionals who have improved their interview skills with InterviewIQ
          </p>
          <Link to="/signup" className="btn btn-light btn-lg px-5">
            Get Started Today
          </Link>
        </div>
      </div>
    </div>
  );
}

export default Home;